[project]
name = "ml-service"
version = "0.1.0"
description = "Student dropout prediction ML project"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "imblearn>=0.0",
    "ipykernel",
    "jupyter",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "uvicorn>=0.52.4",
    "xgboost>=3.4.1",
]

[tool.uv]
package = false
