[project]
name = "ml-work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "catboost>=1.2.10",
    "imblearn>=0.0",
    "lightgbm>=4.7.0",
    "optuna>=4.9.0",
    "pandas>=3.0.3",
    "scikit-learn>=1.9.0",
    "streamlit>=1.59.2",
    "xgboost>=3.3.0",
]
